const colors = {
  light: {
    text: "#1A1A1A",
    tint: "#1C6B3A",
    background: "#F7F3ED",
    foreground: "#1A1A1A",
    card: "#FFFFFF",
    cardForeground: "#1A1A1A",
    primary: "#1C6B3A",
    primaryForeground: "#FFFFFF",
    secondary: "#E4EDE8",
    secondaryForeground: "#1A3D26",
    muted: "#EDE9E2",
    mutedForeground: "#6B6660",
    accent: "#C8A02B",
    accentForeground: "#FFFFFF",
    destructive: "#DC2626",
    destructiveForeground: "#FFFFFF",
    border: "#DDD8D0",
    input: "#DDD8D0",
  },
  dark: {
    text: "#F0EDE6",
    tint: "#4CAF7D",
    background: "#0D1F12",
    foreground: "#F0EDE6",
    card: "#172B1A",
    cardForeground: "#F0EDE6",
    primary: "#4CAF7D",
    primaryForeground: "#0D1F12",
    secondary: "#1E3525",
    secondaryForeground: "#C8E6D2",
    muted: "#1E3525",
    mutedForeground: "#8BAF97",
    accent: "#C8A02B",
    accentForeground: "#0D1F12",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#1E3525",
    input: "#1E3525",
  },
  radius: 10,
};

export default colors;
