export const TAJWEED_RULE_LABELS: Record<string, string> = {
  h: "Hamzah Wasl",
  l: "Lam Shamsiyya",
  n: "Ghunna",
  p: "Idghaam (with Ghunna)",
  m: "Iqlab",
  q: "Qalqala",
  s: "Silah",
  u: "Madd Normal",
  f: "Madd Munfasil",
  k: "Madd Muttasil",
  w: "Idghaam Mutajanisayn",
  y: "Idghaam Mutaqaribayn",
  x: "Idghaam Shafawi",
  a: "Ikhfa Shafawi",
  i: "Ikhfa",
  g: "Ghunna",
};

export const TAJWEED_RULE_DESCRIPTIONS: Record<string, string> = {
  h: "A silent alif that is not pronounced when starting in the middle of speech",
  l: "The lam in ال is assimilated into the following sun letter",
  n: "Heavy nasalization (2 counts) on shadda noon or meem",
  p: "Noon sakinah merges into the next letter with nasalization (2 counts)",
  m: "Noon sakinah is converted to a meem sound with ghunna",
  q: "An echoing bouncing sound on ق ط ب ج د",
  s: "A connecting vowel extending the end of a word",
  u: "2-count elongation on a madd letter",
  f: "Natural 2–5 count elongation before a hamza in the next word",
  k: "Necessary 4–5 count elongation before hamza in the same word",
  w: "Two letters of similar articulation merge together",
  y: "Two letters of near articulation merge together",
  x: "Meem sakinah merges into a following meem",
  a: "Meem sakinah is concealed before ba with ghunna",
  i: "Noon sakinah is concealed before 15 letters with ghunna",
  g: "Nasalization sound held for 2 counts",
};

export const TAJWEED_RULE_COLORS: Record<string, string> = {
  h: "#AAAAAA",
  l: "#AAAAAA",
  n: "#58B800",
  p: "#169200",
  m: "#26BFFD",
  q: "#DD5F60",
  s: "#D500B7",
  u: "#537FFF",
  f: "#4BC8CF",
  k: "#2144C1",
  w: "#A1A000",
  y: "#A1A000",
  x: "#58B800",
  a: "#D500B7",
  i: "#9400A8",
  g: "#58B800",
};
